- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: /bin/bash

- name: Ensure admin user can log in with their key
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_user_key }}"
  tags: update_admin_keys

- name: Ensure admin user is a passwordless sudoer
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ admin_user }}"
    line: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
