- name: Install required system packages
  apt:
    pkg:
      - debian-keyring
      - debian-archive-keyring 
      - apt-transport-https 
      - curl
    state: latest
    update_cache: true

- name: Add Caddy GPG apt Key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present

- name: Add Caddy Repository
  apt_repository:
    repo: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    state: present

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    state: present

- name: Update apt and install caddy
  apt:
    name: caddy
    state: latest
    update_cache: true

- name: Copy Caddyfile
  template:
    src: ../templates/Caddyfile.j2
    dest: "/etc/caddy/Caddyfile"

- name: check caddy is active
  service:
    name: caddy
    state: reloaded
    enabled: yes