---
admin_user: maxine
admin_user_key: https://github.com/mxhzl.keys

mount_dir: /mnt/mxhzl
home_dir: "/home/{{ admin_user }}"

anubis_version: 1.17.0

linkding_data_dir: "{{ mount_dir }}/linkding"
linkding_compose_dir: "{{ home_dir }}/linkding"

forgejo_version: 11.0.0
forgejo_data_dir: "{{ mount_dir }}/forgejo"

mind_electric_version: 1.1.1
mind_electric_compose_dir: "{{ home_dir }}/mind_electric"

file_server_dir: /var/www
