---
- name: Playbook for deploying forgejo
  hosts: production
  remote_user: "{{ admin_user }}"
  become: true
  roles:
    - role: vault
    - role: caddy
    - role: anubis
  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - git
          - git-lfs
        state: present
        update_cache: true

    - name: Copy forgejo anubis .env file
      ansible.builtin.template:
        src: templates/anubis-forgejo.env.j2
        dest: "/etc/anubis/forgejo.env"
        mode: "0644"

    - name: Make sure anubis is running
      ansible.builtin.service:
        enabled: true
        state: started
        name: anubis@forgejo.service

    - name: Download forgejo binary
      ansible.builtin.get_url:
        url: https://codeberg.org/forgejo/forgejo/releases/download/v{{ forgejo_version }}/forgejo-{{ forgejo_version }}-linux-amd64
        dest: /usr/local/bin/forgejo
        mode: "0755"

    - name: Download forgejo gpg key
      ansible.builtin.get_url:
        url: https://codeberg.org/forgejo/forgejo/releases/download/v{{ forgejo_version }}/forgejo-{{ forgejo_version }}-linux-amd64.asc
        dest: /home/maxine/forgejo/forgejo-{{ forgejo_version }}-linux-amd64.asc
        mode: "0755"

    - name: Add key to keyserver
      ansible.builtin.command: gpg --keyserver keys.openpgp.org --recv EB114F5E6C0DC2BCDD183550A4B61A2DC5923710
      register: result
      changed_when: result.rc != 0

    - name: Verify forgejo gpg key
      ansible.builtin.command: gpg --verify /home/maxine/forgejo/forgejo-{{ forgejo_version }}-linux-amd64.asc /usr/local/bin/forgejo
      register: result
      changed_when: result.rc != 0

    - name: Ensure group "git" exists
      ansible.builtin.group:
        name: git
        state: present
        system: true

    - name: Create git user
      ansible.builtin.user:
        name: git
        shell: /bin/bash
        system: true
        create_home: true
        group: git
        comment: "Git Version Control"
        home: /home/git

    - name: Create forgejo data directory
      ansible.builtin.file:
        path: "{{ forgejo_data_dir }}"
        state: directory
        mode: "0750"
        owner: git
        group: git

    - name: Create forgejo config directory
      ansible.builtin.file:
        path: /etc/forgejo
        state: directory
        mode: "0750"
        owner: root
        group: git

    - name: Copy forgejo service file
      ansible.builtin.template:
        src: templates/forgejo.service.j2
        dest: "/etc/systemd/system/forgejo.service"
        mode: "0644"

    - name: Copy forgejo config file
      ansible.builtin.template:
        src: templates/forgejo-app.ini.j2
        dest: "/etc/forgejo/app.ini"
        mode: "0640"
        owner: root
        group: git

    - name: Start forgejo service
      ansible.builtin.service:
        state: started
        enabled: true
        name: forgejo
