---
- hosts: production
  remote_user: "{{ admin_user }}"
  become: yes
  roles:
  - role: mxhzl.vault
  - role: mxhzl.docker
  - role: mxhzl.caddy
  - role: mxhzl.litestream
  - role: mxhzl.anubis
  tasks:
  - name: Copy docker-compose.yml
    template:
      src: templates/forgejo-docker-compose.yml.j2
      dest: "{{ forgejo_dir }}/docker-compose.yml"

  - name: Copy forgejo anubis .env file
    template:
      src: templates/anubis-forgejo.env.j2
      dest: "/etc/anubis/forgejo.env"

  - name: Make sure anubis is running
    service:
      enabled: true
      state: started
      name: anubis@forgejo.service  

  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: forgejo