---
- name: Playbook to deploy linkding
  hosts: production
  remote_user: "{{ admin_user }}"
  become: true
  roles:
    - role: vault
    - role: docker
    - role: caddy
    - role: anubis
  tasks:
    - name: Create directory for docker compose file
      ansible.builtin.file:
        path: "{{ linkding_compose_dir }}"
        state: directory
        mode: "0775"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Create linkding data directory
      ansible.builtin.file:
        path: "{{ linkding_data_dir }}"
        state: directory
        mode: "0755"
        owner: www-data
        group: www-data

    - name: Copy linkding .env file
      ansible.builtin.template:
        src: templates/linkding.env.j2
        dest: "{{ linkding_compose_dir }}/.env"
        mode: "0644"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Copy linkding docker-compose file
      ansible.builtin.template:
        src: templates/linkding-docker-compose.yml.j2
        dest: "{{ linkding_compose_dir }}/docker-compose.yml"
        mode: "0644"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Copy linkding anubis .env file
      ansible.builtin.template:
        src: templates/anubis-linkding.env.j2
        dest: "/etc/anubis/linkding.env"
        mode: "0644"

    - name: Make sure anubis is running
      ansible.builtin.service:
        enabled: true
        state: started
        name: anubis@linkding.service

    - name: Create and start containers
      community.docker.docker_compose_v2:
        project_src: "{{ linkding_compose_dir }}"
        pull: missing
