---
- hosts: production
  remote_user: "{{ admin_user }}"
  become: yes
  roles:
  - role: mxhzl.vault
  - role: mxhzl.docker
  - role: mxhzl.caddy
  - role: mxhzl.litestream
  - role: mxhzl.anubis
  tasks:
  - name: Copy linkding .env file
    template:
      src: templates/linkding.env.j2
      dest: "{{linkding_dir }}/.env"

  - name: Copy linkding docker-compose file
    template:
      src: templates/linkding-docker-compose.yml.j2
      dest: "{{ linkding_dir }}/docker-compose.yml"

  - name: Copy linkding anubis .env file
    template:
      src: templates/anubis-linkding.env.j2
      dest: "/etc/anubis/linkding.env"

  - name: Make sure anubis is running
    service:
      enabled: true
      state: started
      name: anubis@linkding.service  

  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: "{{ linkding_dir }}"