---
- hosts: production
  remote_user: "{{ admin_user }}"
  become: yes
  roles:
  - role: mxhzl.vault
  - role: mxhzl.docker
  tasks:
  - name: Copy docker-compose.yml
    template:
      src: templates/linkding.env.j2
      dest: "{{linkding_dir }}/.env"

  - name: Copy linkding .env file
    template:
      src: templates/linkding-docker-compose.yml.j2
      dest: "{{ linkding_dir }}/docker-compose.yml"

  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: linkding