---
- name: Playbook for deploying The Mind Electric rails app
  hosts: production
  remote_user: "{{ admin_user }}"
  become: true
  roles:
    - role: vault
    - role: docker
    - role: caddy
    - role: anubis
  tasks:
    - name: Create directory for docker compose file
      ansible.builtin.file:
        path: "{{ mind_electric_compose_dir }}"
        state: directory
        mode: "0775"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Copy mind_electric .env file
      ansible.builtin.template:
        src: templates/mind_electric.env.j2
        dest: "{{ mind_electric_compose_dir }}/.env"
        mode: "0644"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Copy mind_electric docker-compose file
      ansible.builtin.template:
        src: templates/mind_electric-docker-compose.yml.j2
        dest: "{{ mind_electric_compose_dir }}/docker-compose.yml"
        mode: "0644"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Copy mind_electric anubis .env file
      ansible.builtin.template:
        src: templates/anubis-mind_electric.env.j2
        dest: "/etc/anubis/mind_electric.env"
        mode: "0644"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Make sure anubis is running
      ansible.builtin.service:
        enabled: true
        state: started
        name: anubis@mind_electric.service

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ mind_electric_compose_dir }}"
        pull: missing
