---
- name: Playbook for running regularly scheduled postgres backups
  hosts: production
  remote_user: "{{ admin_user }}"
  become: true
  roles:
    - role: mxhzl.vault
    - role: mxhzl.op
    - role: mxhzl.b2
  tasks:
    - name: Copy backup script
      ansible.builtin.copy:
        src: templates/scripts/pg_backup/pg_backup.sh
        dest: /usr/local/bin/pg_backup.sh
        mode: "0771"

    - name: Copy backup script .env
      ansible.builtin.copy:
        src: templates/scripts/pg_backup/.env
        dest: "/home/{{ admin_user }}/.pg_backup_env"
        mode: "0771"

    - name: Set op token env var
      ansible.builtin.cron:
        name: "OP_SERVICE_ACCOUNT_TOKEN"
        env: true
        value: "{{ op_service_account_token }}"

    - name: Create cron entry
      ansible.builtin.cron:
        name: "automated pg backups"
        backup: true
        hour: 0
        minute: 0
        weekday: 6
        job: "/usr/local/bin/op run --env-file='/home/{{ admin_user }}/.pg_backup_env' -- /usr/local/bin/pg_backup.sh"
