- name: Copy litesteam config file
  template:
    src: ../templates/litestream.yml.j2
    dest: "/home/maxine/litestream.yml"

- name: Start replication container
  community.docker.docker_container:
    name: litestream
    image: litestream/litestream
    command: replicate
    state: started
    volumes:
      - "{{mount_dir}}:/data"
      - /home/maxine/litestream.yml:/etc/litestream.yml
